use_frameworks!

platform :ios, '9.0'

target 'ESLiveCloud_Example' do
  pod 'ESLiveCloud', :path => '../'
  pod 'AFNetworking'
  pod 'XLForm'

  target 'ESLiveCloud_Tests' do
    inherit! :search_paths

    
  end
end
